### ISSUE TITLE
error message

### ISSUE THREAD

**Issue by steveleeANU** [PurelyWhite/DHM_MATLAB_ANUAOLAB#20]
Undefined function 'downsample' for input arguments of type 'double'.

Error in downsampled_curve (line 17)
        xxx=downsample(xxx,s);

Error in reconstructor/process (line 217)
                    curve_phase = downsampled_curve(phase_unwrap);

Error in test_ui_combined_input/process (line 268)
                    [intensity_no_curve, ~, thickness, lower_limit, upper_limit, frame_peak_height,
                    frame_volume] = app.processing_reconstructor.process(1, centreimg,
                    app.UpperLimitEditField.Value, ...

Error in test_ui_combined_input/ProcessButtonPushed (line 849)
                        app.process(false);
 
Error using matlab.ui.control.internal.controller.ComponentController/executeUserCallback (line 335)
Error while evaluating Button PrivateButtonPushedFcn.

**Comment by zhiduozhang** [comment]
Fixed by installing the Signals Processing Toolbox
