### ISSUE TITLE
Hangs when Processing is Stopped

### ISSUE THREAD

**Issue by DanielLimANU** [PurelyWhite/DHM_MATLAB_ANUAOLAB#22]
GUI hangs when Stop button is pressed during processing.
Issue encountered when analyzing TIFF series in folder, with Quantitative Height and Brightfield export options selected.

**Comment by DanielLimANU** [comment]
Actually- issue isn't it hung. It is saving individual TIFFs of the Hologram even though the option is not selected.

**Comment by zhiduozhang** [comment]
This should be fixed now.
