### ISSUE TITLE
Minor GUI Fixes- Change default values

### ISSUE THREAD

**Issue by DanielLimANU** [PurelyWhite/DHM_MATLAB_ANUAOLAB#27]
![image](https://user-images.githubusercontent.com/73153825/100417092-2e204980-30d4-11eb-80ae-67c80188f2a6.png)
1. Set default exposure to 8000 microseconds
2. Pixel size to 0.176 microns
3. Change to micron symbol

**Comment by zhiduozhang** [comment]
This is fixed.
