### ISSUE TITLE
Crash from ROI Selection

### ISSUE THREAD

**Issue by MildDosage** [PurelyWhite/DHM_MATLAB_ANUAOLAB#8]
Matlab crashed when converting a video with ROI selection. Details attached.

![Matlab Crash from ROI Selection](https://user-images.githubusercontent.com/57782586/68914106-9c3bec00-07b1-11ea-8f16-e1d122c15f05.jpg)

Could be graphics driver, so may be individual case.

**Comment by PurelyWhite** [comment]
Seems working now.
